-- ============================================================================
-- Databricks Table Setup for Knowledge Base Chatbot
-- All tables prefixed with DG for easy identification
-- ============================================================================

-- Set your catalog and schema
USE CATALOG hackathon;
USE SCHEMA hackathon_ctrl_alt_elite;

-- ============================================================================
-- 1. Main Conversations Table (DG_CONVERSATIONS)
-- ============================================================================
CREATE TABLE IF NOT EXISTS DG_CONVERSATIONS (
    conversation_id STRING NOT NULL COMMENT 'Unique identifier for each conversation',
    session_id STRING NOT NULL COMMENT 'Session identifier for grouping conversations',
    user_id STRING DEFAULT 'anonymous' COMMENT 'User identifier',
    timestamp TIMESTAMP NOT NULL COMMENT 'When the conversation occurred',
    user_query STRING NOT NULL COMMENT 'Question asked by the user',
    bot_response STRING NOT NULL COMMENT 'Response generated by the bot',
    query_length INT COMMENT 'Length of user query in characters',
    response_length INT COMMENT 'Length of bot response in characters',
    num_sources INT COMMENT 'Number of source documents used',
    response_time_ms DOUBLE COMMENT 'Response generation time in milliseconds',
    metadata STRING COMMENT 'Additional metadata in JSON format',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT 'Record creation timestamp'
)
USING DELTA
COMMENT 'Main conversation records with queries and responses'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_dg_conv_session
ON DG_CONVERSATIONS (session_id);

CREATE INDEX IF NOT EXISTS idx_dg_conv_timestamp
ON DG_CONVERSATIONS (timestamp);

CREATE INDEX IF NOT EXISTS idx_dg_conv_user
ON DG_CONVERSATIONS (user_id);

-- ============================================================================
-- 2. Conversation Sources Table (DG_CONVERSATION_SOURCES)
-- ============================================================================
CREATE TABLE IF NOT EXISTS DG_CONVERSATION_SOURCES (
    conversation_id STRING NOT NULL COMMENT 'Links to DG_CONVERSATIONS',
    source_rank INT NOT NULL COMMENT 'Ranking of source by relevance (1 = most relevant)',
    file_name STRING NOT NULL COMMENT 'Name of the source document',
    file_path STRING COMMENT 'Full path to the source document',
    similarity_score DOUBLE COMMENT 'Similarity score between query and source',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT 'Record creation timestamp'
)
USING DELTA
COMMENT 'Source documents used for each conversation response'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_dg_sources_conv
ON DG_CONVERSATION_SOURCES (conversation_id);

CREATE INDEX IF NOT EXISTS idx_dg_sources_file
ON DG_CONVERSATION_SOURCES (file_name);

-- ============================================================================
-- 3. Conversation Metrics Table (DG_CONVERSATION_METRICS)
-- ============================================================================
CREATE TABLE IF NOT EXISTS DG_CONVERSATION_METRICS (
    conversation_id STRING NOT NULL COMMENT 'Links to DG_CONVERSATIONS',
    session_id STRING NOT NULL COMMENT 'Session identifier',
    user_id STRING DEFAULT 'anonymous' COMMENT 'User identifier',
    date DATE NOT NULL COMMENT 'Date of conversation (for daily aggregations)',
    query_length INT COMMENT 'Length of user query',
    response_length INT COMMENT 'Length of bot response',
    response_time_ms DOUBLE COMMENT 'Response time in milliseconds',
    num_sources_used INT COMMENT 'Number of sources used in response',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP() COMMENT 'Record creation timestamp'
)
USING DELTA
COMMENT 'Metrics and analytics data for reporting'
TBLPROPERTIES (
    'delta.enableChangeDataFeed' = 'true',
    'delta.autoOptimize.optimizeWrite' = 'true',
    'delta.autoOptimize.autoCompact' = 'true'
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_dg_metrics_date
ON DG_CONVERSATION_METRICS (date);

CREATE INDEX IF NOT EXISTS idx_dg_metrics_session
ON DG_CONVERSATION_METRICS (session_id);

-- ============================================================================
-- 4. Create Views for Easy Querying
-- ============================================================================

-- Comprehensive conversation view with sources
CREATE OR REPLACE VIEW DG_CONVERSATIONS_WITH_SOURCES AS
SELECT
    c.conversation_id,
    c.session_id,
    c.user_id,
    c.timestamp,
    c.user_query,
    c.bot_response,
    c.response_time_ms,
    c.num_sources,
    COLLECT_LIST(
        STRUCT(
            s.source_rank,
            s.file_name,
            s.similarity_score
        )
    ) as sources
FROM DG_CONVERSATIONS c
LEFT JOIN DG_CONVERSATION_SOURCES s ON c.conversation_id = s.conversation_id
GROUP BY
    c.conversation_id,
    c.session_id,
    c.user_id,
    c.timestamp,
    c.user_query,
    c.bot_response,
    c.response_time_ms,
    c.num_sources;

-- Daily metrics summary view
CREATE OR REPLACE VIEW DG_DAILY_METRICS AS
SELECT
    date,
    COUNT(*) as total_conversations,
    COUNT(DISTINCT session_id) as unique_sessions,
    COUNT(DISTINCT user_id) as unique_users,
    AVG(response_time_ms) as avg_response_time_ms,
    PERCENTILE(response_time_ms, 0.5) as median_response_time_ms,
    PERCENTILE(response_time_ms, 0.95) as p95_response_time_ms,
    AVG(query_length) as avg_query_length,
    AVG(response_length) as avg_response_length,
    AVG(num_sources_used) as avg_sources_used
FROM DG_CONVERSATION_METRICS
GROUP BY date
ORDER BY date DESC;

-- ============================================================================
-- 5. Grant Permissions (adjust as needed)
-- ============================================================================
-- GRANT SELECT ON TABLE DG_CONVERSATIONS TO `your_group`;
-- GRANT SELECT ON TABLE DG_CONVERSATION_SOURCES TO `your_group`;
-- GRANT SELECT ON TABLE DG_CONVERSATION_METRICS TO `your_group`;

-- ============================================================================
-- 6. Verify Tables Created
-- ============================================================================
SHOW TABLES LIKE 'DG_%';

-- ============================================================================
-- 7. Table Statistics
-- ============================================================================
DESCRIBE EXTENDED DG_CONVERSATIONS;
DESCRIBE EXTENDED DG_CONVERSATION_SOURCES;
DESCRIBE EXTENDED DG_CONVERSATION_METRICS;

-- ============================================================================
-- Setup Complete!
-- ============================================================================
SELECT 'DG tables created successfully!' as status;